Firestoreからのデータのフェッチ
foodbank-ymg/thanks-web-frontend pull request #22
Opened 2023-07-02 06:47 UTC by Nekodigi

Firestoreからデータをフェッチできるようにし、NEXT_PUBLIC_APP_ENVがDEVELOPMENT、PRODUCTION以外の時はSecret情報がなくても実行できるようにしました。

2023-07-02 07:02 UTC, Nekodigi commented
sampleDataを使用している部分をチェックし、環境変数に応じたフェッチができるように修正しました。

2023-07-02 13:27 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +export const GetPosts = async () => {
どんなPostを取ってるか明示しておきましょう。
```suggestion
export const GetApprovedPosts = async () => {
```

2023-07-02 13:45 UTC, tetsuyanh requested changes
@Nekodigi 
レビューしました。

2023-07-02 13:45 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +export const GetPosts = async () => {
どんなPostを取ってくるか明示しておきましょう。
```suggestion
export const GetApprovedPosts = async () => {
```

2023-07-02 13:45 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +      .withConverter<Post>(postConverter)
承認日時の降順でソートしたいです。
```suggestion
      .collection('posts')
      .where('status', '==', postStatus.APPROVED)
      .orderBy('approved', 'desc')
      .withConverter<Post>(postConverter)
```

項目を足しました。こちら承認した時の更新時にタイムスタンプを記録してください。
https://github.com/foodbank-ymg/thanks-web-backend/wiki/Schema/_compare/ebafb8c7e3283e9749a2336f091f914e261f20f5...fdafb55698ab11f51d4a832c7e95604d7bb9136d

おそらくローカルで実行すると、複合インデクス（status & approvedAt）がない旨のエラーが出ると思います。
そのエラーに、その複合インデクスを作成するリンクが付いてると思います。
そのままブラウザで開いて、指示通りのインデクスを作成してください。

2023-07-02 13:45 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +      createdAt: moment(data.createdAt.toDate()).format('YYYY.MM.DD'),
これJSTになってますかね？なってなかったら対応お願いします。

2023-07-02 13:45 UTC, tetsuyanh commented on src/pages/latest-posts/index.tsx
>  const LATEST_POSTS_QUANTITY = 9
すいません、30件にしたいです。
```suggestion
const LATEST_POSTS_QUANTITY = 30
```

2023-07-04 03:58 UTC, Nekodigi commented on src/lib/firestore/post.ts
> +      .withConverter<Post>(postConverter)
orderBy('approvedAt', 'desc')でしょうか。

2023-07-04 04:09 UTC, Nekodigi commented on src/lib/firestore/post.ts
> +      createdAt: moment(data.createdAt.toDate()).format('YYYY.MM.DD'),
data.createdAtが作成された段階で、JSTになってるはずなのでそこは大丈夫だと思います。
他の場所でJSTになっていない箇所があったので、そこは修正しておきました。

2023-07-05 06:16 UTC, tetsuyanh approved these changes

2023-07-05 06:17 UTC, tetsuyanh commented
@Nekodigi お疲れ様でした。マージしておきます。

2023-07-05 06:17 UTC, merged