month.output
foodbank-ymg/thanks-web-frontend pull request #38
Opened 2023-09-03 12:44 UTC by KAZU0302

@tetsuyanh 
今回担当となったところの何月かを表す部分を作成したので指摘部分などを教えてもらいたいです。よろしくお願いします。

2023-09-05 07:03 UTC, tetsuyanh requested changes
気になって点、指摘しました。Monthの構造は、こうした方がよさそうな感じでスリムに修正しました。

すいませんが、私の作業中の部分もコミットに載せました。
指摘部分を修正次第、マージしましょう。
その後に、投稿一覧の方は別ブランチで着手ということで。

2023-09-05 07:03 UTC, tetsuyanh commented on src/components/Month.tsx
> +      </div>
余計なdivやCSSは排除しました。
「先月」と「次月」を動的なリンカブルにしました。

矢印アイコンはdivにしてtailwindでつくってください。
横幅に応じて変わる部分以外は、global.cssにCSSを直書きするような運用は許容できません。

2023-09-05 07:03 UTC, tetsuyanh commented on src/styles/globals.css
> +  transform: rotate(225deg);
文字や余白の動的な装飾指定以外は、ここにCSS直書きするのはNGです。tsx内でtailwindCSSでお願いします。

2023-09-05 07:03 UTC, tetsuyanh commented on src/pages/latest-posts/index.tsx
> +      </div>
最近のお便りページは、直近の数十件を表示する使用なので、月指定がそもそも不要でした。
一旦、このようにしてます。

2023-09-06 14:36 UTC, KAZU0302 commented
@tetsuyanh 
修正しました。確認よろしくお願いします。

2023-09-11 07:48 UTC, tetsuyanh approved these changes

2023-09-11 07:49 UTC, tetsuyanh commented
@KAZU0302 概ねOK 🙆‍♂️ なのでこれでマージしますね。私の担当分もコミット積ませてもらいました。

2023-09-11 07:49 UTC, merged