add donation_area
foodbank-ymg/thanks-web-frontend pull request #64
Opened 2024-01-13 02:51 UTC by KAZU0302

寄付についての部分を追加しました。改善点、修正点などがあれば教えてもらえるとありがたいです。よろしくお願いします。

2024-01-16 11:37 UTC, tetsuyanh commented
@KAZU0302 
見た目をこのようにしましょう。
flexの子の伸縮はCSS(TailwindCSS)を調べてみてください。
![cap](https://github.com/foodbank-ymg/thanks-web-frontend/assets/1460298/d1d5959c-75c6-4571-ab38-e36f7db927de)

2024-01-16 11:37 UTC, tetsuyanh requested changes
レイアウト修正指摘。

2024-01-17 00:10 UTC, KAZU0302 commented
@tetsuyanh 
修正してみました。確認よろしくお願いします。

2024-01-21 00:10 UTC, tetsuyanh approved these changes

2024-01-21 00:10 UTC, merged

2024-01-21 00:11 UTC, tetsuyanh commented
@KAZU0302 少し修正してマージしました。お疲れ様でした。